### ISSUE TITLE
flag detection: parse libtool .la files

### ISSUE THREAD

**Issue by zmughal** [Perl5-Alien/Alien-Base#74]
In case there are no pkg-config .pc files, but there are libtool .la files. Perhaps create `Alien::Base::Libtool`, like `Alien::Base::PkgConfig`.

See: <https://www.flameeyes.eu/autotools-mythbuster/libtool/lafiles.html>.

**Comment by plicease** [comment]
I'd like to close this because:

 - the link indicates that .la format isn't used in practice by modern tools
 - because the consumption of .la files is low, the likelihood of bugs in exiting .la files is high
 - I don't think allocating the scarce development resources available to AB to this would be wise, though as always patches welcome :)

I will leave it open for a couple more days if anyone wants to comment.
