### ISSUE TITLE
Alien::Base Runtime accessing installation directory

### ISSUE THREAD

**Issue by joergent** [Perl5-Alien/Alien-Base#94]
The installation does not change the directory paths to installed dirs.

[27884] [Tue Nov 25 23:28:48 2014] [warning]: Can't stat
/root/.cpanplus/5.18.4/build/Alien-LibGumbo-0.02/_alien/libgumbo-0.2: Access denied
 at /usr/local/share/perl5/Alien/Base.pm line 296. (/usr/local/share/perl5/Carp.pm:168)

[27884] [Tue Nov 25 23:28:48 2014] [warning]: Could not resolve -lgumbo at
/usr/local/lib64/perl5/HTML/Gumbo.pm line 7. (/usr/local/share/perl5/Carp.pm:168)

**Comment by plicease** [comment]
It appears that ActiveState packages are constructed from the `blib` directory, note here:

http://ppm4.activestate.com/MSWin32-x86-64int/5.20/2000/P/PL/PLICEASE/Alien-FFI-0.08.d/log-20150225T065756.txt

It appears they do not do a `./Build install` at all.  Not really a fan of AS Perl, but this renders unusable virtually anything based on `Alien::Base` for AS Perl.

They set ACTIVESTATE_PPM_BUILD to 1 when building packages.  A workaround would be to install to the appropriate share directory when this variable is set.

**Comment by jberger** [comment]
Argh! Yeah guess we have to, but argh!

**Comment by plicease** [comment]
@jberger I am not entirely sold on this workaround.

**Comment by plicease** [comment]
I did not intend to close this issue.  I think github may have autoclosed it when I merged #114?

**Comment by plicease** [comment]
#114 fixes an unrelated bug specific to PPM, but doing a staged install to blib like this by default would also resolve this bug.  It would also make cpan testers tests not a special case, which is an unending and aggravating source of bugs.  The main argument for the way things are and for installing directly into the "final" location (although keep in mind there is no guarantee for a number of reasons that this actually IS the final location) during the `./Build install` step is that on OS X, dynamic libraries need to be installed in their final location.  I have not witnessed this problem first hand, furthermore when ever possible, static libraries should be used for XS anyway.  I plan on doing some testing to see if I can get dynamic libs to break with this option on OS X, and if it can be fixed in a less exceptional manner.  Please take this opportunity to mention any additional objections.

**Comment by plicease** [comment]
Please see this comment:

https://github.com/Perl5-Alien/Alien-Base/pull/117#issue-69622710

for details on the planned resolution of this fix.

**Comment by plicease** [comment]
#117 now included with the production version of AB, and I believe this to be resolved.
