### ISSUE TITLE
Aliens with tree like dependency

### ISSUE THREAD

**Issue by zmughal** [Perl5-Alien/Alien-Base#95]
On such package that was pointed out to me [here](https://github.com/zmughal/p5-Font-FreeType/issues/11#issuecomment-66176487) is [Alien::SDL2](https://github.com/PerlGameDev/Alien-SDL2). It has to work with multiple libraries to build.

**Comment by plicease** [comment]
I have a working example prototype for how you can do dependency with `alienfile`:

https://github.com/plicease/Alien-Libarchive2/blob/6a15940f2081408dd62ed0421b560aa5c578625f/alienfile

`Alien::Build` already handles this if the dependent project provides a `.pc` file, and the project that you are alienizing uses the `.pc` file.  Unfortunately many projects have broken `.pc` files, and so many other projects just look for things in the default locations instead.  The above example works around this, which demonstrates the workability, but what is interesting here is that the example should be pretty easy to generalize as a plugin.  Good thing, since it is a little unwieldy.  Once such a plugin is available, I think we can close this issue!

**Comment by plicease** [comment]
I believe this addresses the problem for autoconf:

https://metacpan.org/pod/Alien::Build::Plugin::Build::SearchDep

example is here:

https://metacpan.org/source/PLICEASE/Alien-Libarchive3-0.28_02/alienfile
